import { mkdir, readFile, writeFile } from "fs/promises";
import path from "path";

const ROOT = path.resolve(process.cwd());
const OUT = path.join(ROOT, "generated", "assets.ts");

const FONT_FILES = [
  "InterVariable.woff2",
  "NotoSansBengali-Regular.woff",
  "NotoSansDevanagari-Regular.woff",
];

function mimeFor(filename: string): string {
  const ext = path.extname(filename).toLowerCase();
  if (ext === ".png") return "image/png";
  if (ext === ".jpg" || ext === ".jpeg") return "image/jpeg";
  if (ext === ".webp") return "image/webp";
  if (ext === ".svg") return "image/svg+xml";
  if (ext === ".woff2") return "font/woff2";
  if (ext === ".woff") return "font/woff";
  return "application/octet-stream";
}

async function main() {
  const info = JSON.parse(
    await readFile(path.join(ROOT, "data", "info.json"), "utf-8"),
  );

  let logoDataUri: string | null = null;
  if (info.logo) {
    const bytes = await readFile(path.join(ROOT, "public", info.logo));
    logoDataUri = `data:${mimeFor(info.logo)};base64,${bytes.toString("base64")}`;
  }

  const company = {
    companyName: info.companyName ?? "",
    numberLabel: info.numberLabel ?? "",
    numberValue: info.numberValue ?? "",
    addressLines: Array.isArray(info.addressLines) ? info.addressLines : [],
    phone: info.phone ?? "",
    email: info.email ?? "",
    logoDataUri,
  };

  const fonts: Record<string, string> = {};
  for (const file of FONT_FILES) {
    const bytes = await readFile(path.join(ROOT, "public", "fonts", file));
    fonts[file] = `data:${mimeFor(file)};base64,${bytes.toString("base64")}`;
  }

  const code = `// Generated by scripts/gen-assets.ts — do not edit manually.
import type { CompanyInfo } from "../lib/types";

export const COMPANY_INFO: CompanyInfo = ${JSON.stringify(company, null, 2)};

export const FONT_DATA_URIS: Record<string, string> = {
${Object.entries(fonts)
  .map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`)
  .join("\n")}
};
`;

  await mkdir(path.dirname(OUT), { recursive: true });
  await writeFile(OUT, code);
  console.log(
    `Generated ${OUT} (${code.length} bytes, ${Object.keys(fonts).length} fonts, logo: ${logoDataUri ? "yes" : "no"})`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
