import { mkdir, readFile, writeFile } from "fs/promises";
import path from "path";

const ROOT = path.resolve(process.cwd());
const OUT = path.join(ROOT, "generated", "assets.ts");

const FONT_FILES = [
  "InterVariable.woff2",
  "NotoSansBengali-Regular.woff",
  "NotoSansDevanagari-Regular.woff",
];

// Cloudflare Workers have no filesystem access at request time, so the font
// and logo bytes have to be baked into the module as base64 at build time.
// Netlify and Vercel run on Node, where `public/` ships alongside the
// function and can just be `readFileSync` at runtime — so on those platforms
// we generate a tiny module that reads the files lazily instead of inlining
// ~600KB of base64 into the compiled server bundle.
const isCloudflare = process.env.CF_PAGES === "1";

function mimeFor(filename: string): string {
  const ext = path.extname(filename).toLowerCase();
  if (ext === ".png") return "image/png";
  if (ext === ".jpg" || ext === ".jpeg") return "image/jpeg";
  if (ext === ".webp") return "image/webp";
  if (ext === ".svg") return "image/svg+xml";
  if (ext === ".woff2") return "font/woff2";
  if (ext === ".woff") return "font/woff";
  return "application/octet-stream";
}

async function buildInlinedCode(company: {
  companyName: string;
  numberLabel: string;
  numberValue: string;
  addressLines: string[];
  phone: string;
  email: string;
}, logoPath: string | null): Promise<string> {
  let logoDataUri: string | null = null;
  if (logoPath) {
    const bytes = await readFile(path.join(ROOT, "public", logoPath));
    logoDataUri = `data:${mimeFor(logoPath)};base64,${bytes.toString("base64")}`;
  }

  const fonts: Record<string, string> = {};
  for (const file of FONT_FILES) {
    const bytes = await readFile(path.join(ROOT, "public", "fonts", file));
    fonts[file] = `data:${mimeFor(file)};base64,${bytes.toString("base64")}`;
  }

  return `// Generated by scripts/gen-assets.ts — do not edit manually.
import type { CompanyInfo } from "../lib/types";

export const COMPANY_INFO: CompanyInfo = ${JSON.stringify({ ...company, logoDataUri }, null, 2)};

export const FONT_DATA_URIS: Record<string, string> = {
${Object.entries(fonts)
  .map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`)
  .join("\n")}
};
`;
}

function buildRuntimeReadCode(company: {
  companyName: string;
  numberLabel: string;
  numberValue: string;
  addressLines: string[];
  phone: string;
  email: string;
}, logoPath: string | null): string {
  return `// Generated by scripts/gen-assets.ts — do not edit manually.
import { readFileSync } from "node:fs";
import path from "node:path";
import type { CompanyInfo } from "../lib/types";

function dataUri(relPath: string, mime: string): string {
  const bytes = readFileSync(path.join(process.cwd(), "public", relPath));
  return \`data:\${mime};base64,\${bytes.toString("base64")}\`;
}

export const COMPANY_INFO: CompanyInfo = {
  companyName: ${JSON.stringify(company.companyName)},
  numberLabel: ${JSON.stringify(company.numberLabel)},
  numberValue: ${JSON.stringify(company.numberValue)},
  addressLines: ${JSON.stringify(company.addressLines)},
  phone: ${JSON.stringify(company.phone)},
  email: ${JSON.stringify(company.email)},
  logoDataUri: ${logoPath ? `dataUri(${JSON.stringify(logoPath)}, ${JSON.stringify(mimeFor(logoPath))})` : "null"},
};

export const FONT_DATA_URIS: Record<string, string> = {
${FONT_FILES.map(
  (file) =>
    `  ${JSON.stringify(file)}: dataUri(${JSON.stringify(`fonts/${file}`)}, ${JSON.stringify(mimeFor(file))}),`,
).join("\n")}
};
`;
}

async function main() {
  const info = JSON.parse(
    await readFile(path.join(ROOT, "data", "info.json"), "utf-8"),
  );

  const company = {
    companyName: info.companyName ?? "",
    numberLabel: info.numberLabel ?? "",
    numberValue: info.numberValue ?? "",
    addressLines: Array.isArray(info.addressLines) ? info.addressLines : [],
    phone: info.phone ?? "",
    email: info.email ?? "",
  };
  const logoPath: string | null = info.logo ?? null;

  const code = isCloudflare
    ? await buildInlinedCode(company, logoPath)
    : buildRuntimeReadCode(company, logoPath);

  await mkdir(path.dirname(OUT), { recursive: true });
  await writeFile(OUT, code);
  console.log(
    `Generated ${OUT} (${code.length} bytes, mode: ${isCloudflare ? "inlined (Cloudflare)" : "runtime read (Node)"}, ${FONT_FILES.length} fonts, logo: ${logoPath ? "yes" : "no"})`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
